name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Set the Node.js version (use the version that your project uses)

      # Install dependencies and build the project
      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          user_name: "J. Shapiro"
          user_email: "jshapi4@users.noreply.github.com"
          cname: emishapirophotography.com
